apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: webapp
spec:
    ports:
    - port: 3306
    selector:
       app: webapp
       tier: mysql
    clusterIP: None
---
  
apiVersion: apps/v1
kind: Deployment
metadata:
      name: mysqldb
spec:
      selector:
        matchLabels:
          app: webapp
          tier: mysql
      strategy:
        type: Recreate
      template:
        metadata:
           labels:
              app: webapp
              tier: mysql
        spec:
           containers:
           - image: mysql:5.6
             name: mysqldb
             env:
             - name: MYSQL_ROOT_PASSWORD
               value: welcome123
             - name: MYSQL_DATABASE
               value: mysql_db                
             - name: MYSQL_USER
               value: root
             args: ["--default-authentication-plugin=mysql_native_password"]
             ports:
             - containerPort: 3306
               name: mysqldb
             volumeMounts:
             - name: mysql-initdb
               mountPath: /docker-entrypoint-initdb.d
           volumes:
           - name: mysql-initdb
             configMap:
                  name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: mysql-initdb-config
data:
   initdb.sql: |
      CREATE DATABASE IF NOT EXISTS `mysql_db`;
      USE `mysql_db`;
      CREATE TABLE IF NOT EXISTS `USER` (`id` int(10) unsigned NOT NULL auto_increment, `first_name` varchar(45) NOT NULL, `last_name` varchar(45) NOT NULL, `email` varchar(45) NOT NULL, `username` varchar(45) NOT NULL, `password` varchar(45) NOT NULL, `regdate` date NOT NULL, PRIMARY KEY  (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

